# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('PPforest2_timesTwo', PACKAGE = 'PPforest2', x)
}

PPpred <- function(TRstr, TRprnode, TRspl, testdata) {
    .Call('PPforest2_PPpred', PACKAGE = 'PPforest2', TRstr, TRprnode, TRspl, testdata)
}

imposoon <- function(train, classes, oobid, permute, trees, noob, TRstrL, TRsplL, TRprnodeL) {
    .Call('PPforest2_imposoon', PACKAGE = 'PPforest2', train, classes, oobid, permute, trees, noob, TRstrL, TRsplL, TRprnodeL)
}

